name: Generate Resume JSON
on:
  push:
    branches:
      - main
      - test

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files in the working directory
        run: dir
        shell: cmd

      - name: Check if config.json exists
        run: |
         if (!(Test-Path -Path "config.json")) {
          Write-Host "config.json is missing"
          exit 1
         } else {
           Write-Host "config.json exists"
           Write-Host "Content of config.json:"
           Get-Content -Path "config.json" | Write-Host
         }
        shell: pwsh

      - name: Read gist_id setting from JSON
        id: read_json_gistid_value
        run: echo "GISTID=$(jq -r '.deployment.gist_id' config.json)" >> $GITHUB_ENV

      - name: Read dry-run setting from JSON
        id: read_json_dryrun_value
        run: echo "DRYRUN=$(jq -r '.environment.dryrun' config.json)" >> $GITHUB_ENV

      - name: Run PowerShell Script with Debug
        run: |
            pwsh -NoProfile -Command "$VerbosePreference = 'Continue'; $DebugPreference = 'Continue'; .\GenerateResume.ps1 -Verbose -Debug"
   
        
        
      # - name: Execute PowerShell script
      #   run: .\GenerateResume.ps1
      #   shell: pwsh

      - name: Update Resume Gist
        if: ${{ env.DRYRUN == '0' }}
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: ${{ env.GISTID }}
          file_path: resume.json

permissions:
  contents: read